<!-- template begin: view/common/pagination -->
<?php
$translate = $this->plugin('translate');

// Do not emit the sort default flags.
$removeQueries = ['page', 'sort_by_default', 'sort_order_default'];
// Do not emit sorts if the corresponding default sort flags are set.
if (isset($query['sort_by_default'])) {
    $removeQueries[] = 'sort_by';
}
if (isset($query['sort_order_default'])) {
    $removeQueries[] = 'sort_order';
}

// crée une variable pour l'URL de la page courante
$currentPageUrl = $_SERVER['REQUEST_URI'];
?>
<?php if ($totalCount): ?>
<nav class="pagination bulma-pagination" role="navigation">
  <ul class="bulma-pagination-list is-justify-content-center">
  <?php if ($currentPage != 1): ?>
    <li>
      <a class="first bulma-pagination-link" href="<?php echo $firstPageUrl; ?>" title="<?php echo $translate('Start'); ?>">
        <span class="visually-hidden"><?php echo $translate('Start'); ?></span>
        <span aria-hidden="true">1</span>
      </a>
    </li>
    <?php if ($currentPage > 3): ?>
    <li><span class="bulma-pagination-ellipsis">&hellip;</span></li>
    <?php endif; ?>
    <?php if ($currentPage > 4): ?>
      <?php
      $backwardPage = intdiv($currentPage, 2);
      $backwardPageUrl = preg_replace('/([\?&]+)page=\d+/', "$1page=$backwardPage", $currentPageUrl);
      ?>
    <li>
      <a class="next bulma-pagination-link" href="<?php echo $backwardPageUrl; ?>" title="<?php echo $translate('Backward'); ?>">
        <span class="visually-hidden"><?php echo $translate('Backward'); ?></span>
        <span aria-hidden="true"><i class="fa-solid fa-angles-left"></i></span>
      </a>
    </li>
    <?php endif; ?>
    <?php if ($currentPage > 2): ?>
    <li>
      <a class="previous bulma-pagination-link" href="<?php echo $previousPageUrl; ?>" title="<?php echo $translate('Previous'); ?>">
        <span class="visually-hidden"><?php echo $translate('Previous'); ?></span>
        <?php if ($currentPage === 3): ?>
        <span aria-hidden="true"><?php echo($currentPage - 1); ?></span>
        <?php else: ?>
        <span aria-hidden="true"><i class="fa-solid fa-angle-left"></i></span>
        <?php endif; ?>
      </a>
    </li>
    <?php endif; ?>
  <?php endif; ?>
    <li>
      <a class="bulma-pagination-link is-active" href="<?php echo $currentPageUrl; ?>" title="<?php echo $translate('Page courante'); ?>">
        <span class="visually-hidden"><?php echo $translate('Current'); ?></span>
        <span aria-hidden="true"><?php echo $currentPage; ?></span>
      </a>
    </li>
  <?php if ($currentPage < $pageCount): ?>
    <?php if ($currentPage < $pageCount - 1): ?>
    <li>
      <a class="next bulma-pagination-link" href="<?php echo $nextPageUrl; ?>" title="<?php echo $translate('Next'); ?>">
        <span class="visually-hidden"><?php echo $translate('Next'); ?></span>
        <?php if ($currentPage === ($pageCount - 2)): ?>
        <span aria-hidden="true"><?php echo($currentPage + 1); ?></span>
        <?php else: ?>
        <span aria-hidden="true"><i class="fa-solid fa-angle-right"></i></span>
        <?php endif; ?>
      </a>
    </li>
    <?php endif; ?>
    <?php if ($pageCount - $currentPage > 4): ?>
      <?php
      $forwardPage = intdiv($pageCount - $currentPage, 2) + $currentPage;
      $forwardPageUrl = preg_replace('/([\?&]+)page=\d+/', "$1page=$forwardPage", $currentPageUrl);
      ?>
    <li>
      <a class="next bulma-pagination-link" href="<?php echo $forwardPageUrl; ?>" title="<?php echo $translate('Forward'); ?>">
        <span class="visually-hidden"><?php echo $translate('Forward'); ?></span>
        <span aria-hidden="true"><i class="fa-solid fa-angles-right"></i></span>
      </a>
    </li>
    <?php endif; ?>
    <?php if ($pageCount - $currentPage > 2): ?>
    <li class="p-1"><span class="bulma-pagination-ellipsis">&hellip;</span></li>
    <?php endif; ?>
    <li>
      <a class="last bulma-pagination-link" href="<?php echo $lastPageUrl; ?>" title="<?php echo $translate('End'); ?>">
        <span class="visually-hidden"><?php echo $translate('End'); ?></span>
        <span aria-hidden="true"><?php echo $pageCount; ?></span>
      </a>
    </li>
  <?php endif; ?>
  </ul>
</nav>
<?php endif; ?>
<!-- template end: view/common/pagination -->
