<!-- template begin: common/forms/newsletter -->
<form  id="cm-form-news" name="cm-form-news" method="post" action="" class="inf-form">
  <input type="email" name="email" style="display:none" />
  <input type="hidden" name="key" value="">
  <input type="hidden" name="webform_id" value="">
  <div class="inf-main_78f7a8d2193741fa2bfb74ea06e162b4">
    <div class="inf-content">
      <div class="bulma-field">
        <p>Je veux recevoir la newsletter</p>
        <div class="inf-input inf-input-text bulma-control bulma-has-icons-left cm-form-email">
          <input class="bulma-input" type="email" placeholder="Mon e-mail" value="" name="inf[1]" data-inf-meta="1" data-inf-error="" required="required">
          <span class="bulma-icon bulma-is-small bulma-is-left">
            <i class="fas fa-envelope"></i>
          </span>
        </div>
      </div>
      <div class="bulma-field">
        <div class="bulma-control">
          <div class="bulma-checkbox">
            <input type="checkbox" id="cm-form-news-cgu">
            J'ai lu et j'accepte <a href="/notice#cgu">les CGU</a>
          </div>
        </div>
      </div>
      <script src="https://eu.altcha.org/js/latest/altcha.min.js" type="module" defer></script>
      <altcha-widget hidelogo hidefooter floating challengeurl="https://newsletter.infomaniak.com/v3/altcha-challenge" ></altcha-widget>
      <script src="https://newsletter.storage5.infomaniak.com/mcaptcha/altcha.js" defer> </script>
      <div class="bulma-field">
        <div class="bulma-control">
          <div class="inf-submit">
            <input class="bulma-button" id="cm-form-news-submit" type="submit" name="" value="Valider" disabled="">
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
<script src="<?php echo $this->assetUrl('js/newsletter.js'); ?>"></script>
<!-- template end: common/forms/newsletter -->
