<!-- template begin: common/forms/newsletter -->
<form  id="cm-form-news" name="cm-form-news" method="post" action="<?php echo $this->themeSetting('newsletter_form_action'); ?>" class="inf-form">
  <input type="email" name="email" style="display:none" />
  <input type="hidden" name="key" value="<?php echo $this->themeSetting('newsletter_key_value'); ?>">
  <input type="hidden" name="webform_id" value="<?php echo $this->themeSetting('newsletter_webform_id_value'); ?>">
  <div class="<?php echo $this->themeSetting('newsletter_div_class'); ?>">
    <div class="inf-content">
      <div class="bulma-field">
        <p>Je veux recevoir la newsletter</p>
        <div class="inf-input inf-input-text bulma-control bulma-has-icons-left cm-form-email">
          <input class="bulma-input" type="email" placeholder="Mon e-mail" value="" name="inf[1]" data-inf-meta="1" data-inf-error="" required="required">
          <span class="bulma-icon bulma-is-small bulma-is-left">
            <i class="fas fa-envelope"></i>
          </span>
        </div>
      </div>
      <div class="bulma-field">
        <div class="bulma-control">
          <div class="bulma-checkbox">
            <input type="checkbox" id="cm-form-news-cgu">
            J'ai lu et j'accepte <a href="/notice?a=cgu">les CGU</a>
          </div>
        </div>
      </div>
      <?php echo $this->themeSetting('newsletter_altcha_block'); ?>
      <div class="bulma-field">
        <div class="bulma-control">
          <div class="inf-submit">
            <input class="bulma-button" id="cm-form-news-submit" type="submit" name="" value="Valider" disabled="">
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
<script src="<?php echo $this->assetUrl('js/newsletter.js'); ?>"></script>
<!-- template end: common/forms/newsletter -->
