<!-- template begin: common/forms/newsletter -->
<form  id="cm-form-news" name="cm-form-news" method="post" action="" class="inf-form">
  <input type="email" name="email" style="display:none" />
  <input type="hidden" name="key" value="">
  <input type="hidden" name="webform_id" value="">
  <div class="inf-main">
    <div class="inf-content">
      <div class="bulma-field">
        <p>I subscribe to your newsletter</p>
        <div class="inf-input inf-input-text bulma-control bulma-has-icons-left cm-form-email">
          <input class="bulma-input" type="email" placeholder="E-mail" value="" name="inf[1]" data-inf-meta="1" data-inf-error="" required="required">
          <span class="bulma-icon bulma-is-small bulma-is-left">
            <i class="fas fa-envelope"></i>
          </span>
        </div>
      </div>
      <div class="bulma-field">
        <div class="bulma-control">
          <div class="bulma-checkbox">
            <input type="checkbox" id="cm-form-news-cgu">
            I have read and I accept <a href="/notice#cgu">the conditions</a>
          </div>
        </div>
      </div>
      <div class="bulma-field">
        <div class="bulma-control">
          <div class="inf-submit">
            <input class="bulma-button" id="cm-form-news-submit" type="submit" name="" value="Valider" disabled="">
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
<script src="<?php echo $this->assetUrl('js/newsletter.js'); ?>"></script>
<!-- template end: common/forms/newsletter -->
