<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

$this->htmlElement('body')->appendAttribute('class', 'item-set resource browse');
?>

<div class="bulma-hero bulma-is-medium">
  <div class="bulma-hero-body">
    <div class="cm-enlum has-text-centered py-2">
      <img src="<?php echo $this->assetUrl('img/papyrus-icon.png'); ?>" alt="Papyrus">
    </div>
    <p class="bulma-subtitle has-text-centered">Découvrir nos</p>
    <p class="bulma-title has-text-centered"><?php echo $translate('Item sets'); ?></p>
  </div>
</div>

<?php $this->trigger('view.browse.before'); ?>

<div class="bulma-section px-0 cm-is-gris-doux">
  <ul class="resource-list itemset-list cm-flk-block" data-freescroll="true">
  <?php
  $headingTerm = $this->siteSetting('browse_heading_property_term');
  $bodyTerm = $this->siteSetting('browse_body_property_term');
  foreach ($itemSets as $itemSet):
      $heading = $headingTerm ? $itemSet->value($headingTerm, ['default' => $translate('[Untitled]'), 'lang' => $valueLang]) : $itemSet->displayTitle(null, $valueLang);
      $body = $bodyTerm ? $itemSet->value($bodyTerm, ['lang' => $valueLang]) : $itemSet->displayDescription(null, $valueLang);
  ?>
      <li class="item-set resource cm-flk-cell">
        <div class="cm-item-img">
          <?php
          echo $thumbnail($itemSet, 'large');
          ?>
        </div>
        <div class="cm-item-title cm-oneline">
        <?php
          $linkContent = sprintf('<h3 class="resource-name">%s</h3>', $escape($heading));
          echo $itemSet->linkRaw($linkContent, null, ['class' => 'resource-link']);
          ?>
        </div>
          <?php // if ($body): /?>
          <?php /*
          <div class="description"><?php echo $escape($body); ?></div>
          */?>
          <?php //endif; ?>
      </li>
  <?php endforeach; ?>
  </ul>
</div>

<?php $this->trigger('view.browse.after'); ?>
