<!-- template begin: omeka/site/item-set/browse -->
<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;
$query = $this->params()->fromQuery();

$this->htmlElement('body')->appendAttribute('class', 'item-set resource browse');

// get the background image of the page header if set in the theme settings
$bgImageUrl = $this->themeSettingAssetUrl('item_sets_background') ?: $this->assetUrl('img/media-generic.jpg');

?>

<!-- build the page content with the same structure as for a site page -->

<div class="blocks">
  <div class="blocks-inner page-layout-normal" style="">
    <div class="block block-blockGroup bulma-hero cm-page-header cm-is-dark-block has-background" style="background-image: url('<?php echo $bgImageUrl; ?>');">
      <div class="block block-html bulma-hero-body">
        <p class="bulma-subtitle has-text-centered">Découvrez nos</p>
        <p class="bulma-title has-text-centered"><?php echo $translate('Item sets'); ?></p>
      </div>
    </div>
    <div class="block block-blockGroup bulma-section">
      <div class="block block-html">
        <div class="bulma-container bulma-is-max-tablet has-text-centered is-size-5">
          <div class="bulma-container bulma-is-max-tablet has-text-centered is-size-5 mb-6"><?php echo $this->themeSetting('item_sets_chapo'); ?></div>
        </div>
        <p class="bulma-container bulma-is-max-desktop has-text-centered"><?php echo $this->themeSetting('item_sets_description'); ?></p>
      </div>
    </div>
    <?php $this->trigger('view.browse.before');?>
    <div class="block block-blockGroup bulma-section">
      <div class="bulma-container bulma-is-max-desktop cm-has-color-violet">
        <?php // add item sets
        echo $this->partial('common/block-layout/browse-twinsets', [
          'resources' => $itemSets,
          'query' => $query
        ]);
        ?>
      </div>
    </div>
    <?php $this->trigger('view.browse.after'); ?>
  </div>
</div>
<!-- template end: omeka/site/item-set/browse -->
