<!-- template begin: omeka/site/item/browse -->
<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
  $this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
  $this->htmlElement('body')->appendAttribute('class', 'item-set');
  $query['item_set_id'] = $itemSet->id();
endif;
?>

<?php if ($itemSetShow): ?>
    <?php echo $this->pageTitle($itemSet->displayTitle(null, $valueLang), 2); ?>
    <h3><?php echo $translate('Item set'); ?></h3>
    <div class="metadata">
        <?php echo $this->resourcePageBlocks($itemSet)->getBlocks(); ?>
    </div>
    <div class="item-set-items">
    <?php echo '<h3>' . $escape($translate('Items')) . '</h3>'; ?>
<?php else: ?>
    <?php echo $this->pageTitle($translate('Items'), 2); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
    <?php echo $this->browse()->renderSortSelector('items'); ?>
    <?php //echo $this->browse()->renderSortSelector(['title' => $translate('Title'), 'created' => $translate('Created')]); ?>
</div>
<?php echo ($itemSetShow) ? '</div>' : ''; ?>

<?php $this->trigger('view.browse.before'); ?>
<?php
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');

// alimente la structure de navigation
$itemNav = [];      // structure de navigation des items
$itemSave = null;   // stocke l'id de l'item en cours
foreach ($items as $item) {
  //$itemId = $item->value('dcterms:identifier');
  $itemId = $item->id();
  $itemNav[$itemId] = ['itemPrev' => $itemSave, 'itemNext' => null];
  if ($itemSave) {
    $itemNav[$itemSave]['itemNext'] = $itemId;
  }
  $itemSave = $itemId;
}
// stocke la structure de navigation dans une variable de session --> utilisée dans le template item/show.phtml
$_SESSION['itemNav'] = $itemNav;
// stocke l'id de la collection en cours ssi elle est définie
if (isset($itemSet)) {
  $_SESSION['itemSet'] = $itemSet->id();
}

// affiche les items
echo $this->partial('common/block-layout/browse-cards', [
  'resources' => $items,
  'query' => $query
]);
?>

<?php $this->trigger('view.browse.after'); ?>
<?php echo $this->pagination(); ?>
<!-- template end: omeka/site/item/browse -->
