<!-- template begin: omeka/site/page/show -->
<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', $pageBodyClass);
$this->pageTitle($page->title(), 2);
$nav = $site->publicNav();
// CM begin
// on doit ajouter les lignes ci-dessous si le module Clean URL est actif (cf https://forum.omeka.org/t/active-page-not-set-when-clean-url-is-active/28149)
$thisPage = $nav->getContainer()->findOneBy('label', $page->title());
if($thisPage !== null):
  $thisPage->setActive(true);
endif;
// CM end
$activePage = $nav->findActive($nav->getContainer());

switch ($this->siteSetting('subnav_display')) {
    case 'show';
        $displaySubnav = $this->displayNavigation;
        break;
    case 'hide':
        $displaySubnav = false;
        break;
    default:
        $displaySubnav = $this->displayNavigation && $activePage && $activePage['page']->hasPages();
}
$showPagePagination = $this->siteSetting('show_page_pagination', true);
?>

<?php if ($activePage): ?>
<?php if ($activePage['depth'] !== 0): ?>
<nav class="breadcrumbs"><?php echo $nav->breadcrumbs(); ?></nav>
<?php endif; ?>
<?php endif; ?>

<?php if ($activePage): ?>
<?php if ($displaySubnav): ?>
<nav class="sub-menu"><?php echo $nav->menu()->renderSubMenu(); ?></nav>
<?php endif; ?>
<?php endif; ?>

<?php $this->trigger('view.show.before'); ?>
<div class="blocks">
    <?php echo $this->content; ?>
</div>
<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
<?php echo $this->sitePagePagination(); ?>
<?php endif; ?>
<!-- template end: omeka/site/page/show -->
