<!-- template begin: common/block-layout/browse-cards -->
<?php
$escape = $this->plugin('escapeHtml');

$title = isset($title) ? $title : null;
$description = isset($description) ? $description : null;
$pagination = isset($pagination) ? $pagination : null;
$linkText = isset($linkText) ? $linkText : null;
$resourceType = isset($resourceType) ? $resourceType : null;
$totalResults = (isset($totalResults) && $totalResults) ? $totalResults : count($resources);
$page = isset($query['page']) ? $query['page'] : 1;
$perPage = isset($query['per_page']) ? $query['per_page'] : $totalResults;
$limit = isset($query['limit']) ? $query['limit'] : 12;
$more = (($page * $perPage) >= $limit);
$offsetStart = ($page - 1) * $perPage + 1;
$offsetEnd = $page * $perPage;
$offsetEnd = ($offsetEnd > $totalResults) ? $totalResults : $offsetEnd;
?>

<div class="preview-block bulma-section px-0 cm-is-gris-doux">
  <div class="bulma-container">
    <ul class="resource-list preview cm-iso-block">
      <?php if ($title || $description): ?>
      <li class="resource cm-iso-cell cm-iso-wide bulma-card">
        <div class="cm-item-img bulma-card-image">
        </div>
        <div class="bulma-card-content">
          <div class="cm-item-title bulma-title is-size-6">
          </div>
          <div class="bulma-content">
            <?php if ($title): ?><h2 class="has-text-centered is-size-2"><?php echo $escape($title); ?></h2><?php endif; ?>
            <?php if ($description): ?><p class="has-text-centered"><?php echo $escape($description); ?></p><?php endif; ?>
            <!-- <?php echo sprintf('%s - %s / %s [%s]', $offsetStart, $offsetEnd, $totalResults, $limit); ?> -->
            <!-- <?php echo sprintf('page %s - perPage %s', $page, $perPage); ?> -->
          </div>
        </div>
      </li>
      <?php endif; ?>
      <?php foreach ($resources as $resource): ?>
      <li class="resource <?php echo $resource->resourceName(); ?> cm-iso-cell bulma-card">
        <?php echo $this->LinkPretty($resource, null, 'large', true, true); ?>
      </li>
      <?php endforeach; ?>
    </ul>
    <?php if ($pagination): ?>
    <div class="browse-controls">
      <?php echo $pagination; ?>
    </div>
    <?php endif; ?>
    <?php if ($linkText): ?>
      <?php
      //$linkMore = $this->hyperlink($linkText, $this->url('site/resource', ['controller' => $resourceType, 'action' => 'browse'], ['query' => $query], true));
      $linkMore = $this->hyperlink($linkText, $this->url('site/resource', ['controller' => $resourceType, 'action' => 'browse'], null, true));
       ?>
       <div class="bulma-content has-text-centered">
         <button type="submit" class="button bulma-button bulma-is-medium mt-5"><?php echo $linkMore; ?></button>
       </div>
    <?php endif; ?>
  </div>
</div>
<!-- template end: common/block-layout/browse-cards -->
