<!-- template begin: common/block-layout/browse-preview -->
<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');
$api = $this->plugin('api');

$query = $this->query;  //NB: toujours null --> si on en a vraiment besoin, trouver un moyen de la récupérer en utilisant $resources
$heading = isset($this->heading) ? explode('|', $this->heading, 2) : null;
$title = $heading ? (isset($heading[0]) ? $heading[0] : null) : null;
$description = $heading ? (isset($heading[1]) ? $heading[1] : null) : null;
$totalResults = count($resources);

if ($totalResults === 0) {
  echo '<pre>Aucun résultat</pre>';
  return;
}

$partial = 'browse-cards';

$class = $block->layoutDataValue('class');
if ($class) {
  $blockClasses = explode(' ', $class);
  if (in_array('browse-flk', $blockClasses)) {
    $partial = 'browse-flk';
  }
}

echo $this->partial('common/block-layout/' . $partial, [
  'resources' => $resources,
  'resourceType' => $this->resourceType,
  'query' => $query,
  'title' => $title,
  'description' => $description,
  'totalResults' => $totalResults,
  'linkText' => $linkText,
  'pagination' => $this->pagination()
]);
?>
<!-- template end: common/block-layout/browse-preview -->
