<!-- template begin: common/block-layout/browse-preview -->
<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');
$api = $this->plugin('api');

$query = $this->query;
$heading = isset($this->heading) ? explode('|', $this->heading, 2) : null;
$title = $heading ? (isset($heading[0]) ? $heading[0] : null) : null;
$description = $heading ? (isset($heading[1]) ? $heading[1] : null) : null;
$response = $api->search('items', $query);
$totalResults = $response->getTotalResults();

if ($totalResults === 0) {
  echo '<pre>Aucun résultat</pre>';
  return;
}

echo $this->partial('common/block-layout/browse-cards', [
  'resources' => $resources,
  'query' => $query,
  'title' => $title,
  'description' => $description,
  'totalResults' => $totalResults
]);

if ($this->linkText):
  echo $this->hyperlink($this->linkText, $this->url(
    'site/resource', ['controller' => $this->resourceType, 'action' => 'browse'], ['query' => $this->query], true
  ));
endif;
?>
<!-- template end: common/block-layout/browse-preview -->
