<!-- template begin: common/block-layout/browse-flk -->
<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');
?>

<div class="preview-block bulma-section px-0">
  <div class="bulma-container">
    <ul class="resource-list preview cm-flk-block" data-lightbox="<?php echo $lightBox ? 'true' : 'false' ?>">
      <?php foreach ($resources as $resource): ?>
      <li class="resource <?php echo $resource->resourceName(); ?> cm-flk-cell">
        <div class="cm-item-img">
          <?php
          $linkImg = $thumbnail($resource, 'large') ?: ('<img src="' . $this->assetUrl('img/media-generic.jpg') . '" alt="' . $resource->resourceName() . '">');
          echo $lightBox ? "<a>$linkImg</a>" : $linkImg;
          ?>
        </div>
        <div class="cm-item-title cm-oneline">
          <?php
          $linkContent = sprintf('<h3 class="resource-name">%s</h3>', $resource->displayTitle());
          echo $lightBox ? $linkContent : $resource->linkRaw($linkContent, null, ['class' => 'resource-link']);
          ?>
        </div>
      </li>
      <?php endforeach; ?>
    </ul>
  </div>
</div>
<!-- template end: common/block-layout/browse-flk -->
