<!-- template begin: common/resource-page-block-layout/media-list -->
<?php
$resourceMedia = $resource->media();
?>
<?php if ($resourceMedia): ?>
<dl class="media-list cm-flk-block" data-freescroll="false" data-autoplay="5000" data-wraparound="true" data-fade="true" data-prevnextbuttons="false" data-draggable="false">
    <div class="property">
        <dt>
          <?php echo $this->translate('Media'); ?>
        </dt>
        <?php foreach ($resourceMedia as $media): ?>
        <dd class="value cm-flk-cell" data-id="<?php echo $media->id(); ?>" data-source="<?php echo $media->source(); ?>" data-extension="<?php echo $media->extension(); ?>" data-mediaType="<?php echo $media->mediaType(); ?>">
          <?php echo $this->LinkPretty($resource, $media, 'large', 'media'); ?>
        </dd>
        <?php endforeach; ?>
    </div>
</dl>
<?php else: ?>
<dl class="media-list cm-flk-block" data-freescroll="false" data-autoplay="5000" data-wraparound="true" data-fade="true" data-prevnextbuttons="false" data-draggable="false">
    <div class="property">
        <dt>
          <?php echo $this->translate('Media'); ?>
        </dt>
        <dd class="value cm-flk-cell" data-source="" data-extension="" data-mediaType="">
          <?php echo $this->LinkPretty($resource, null, 'large', 'media'); ?>
        </dd>
    </div>
</dl>
<?php endif; ?>

<!-- backend > frontend -->
<script>
omekaVars.tileSources = [
  <?php foreach ($resourceMedia as $media): ?>
    '/iiif/2/<?php echo $media->id(); ?>/info.json',
  <?php endforeach; ?>
];
</script>

<!-- template end: common/resource-page-block-layout/media-list -->
