<!-- template begin: common/footer/footer -->

<?php
$nav = $site->publicNav();
$container = $nav->getContainer();
//$page = $container->findOneBy('o:slug', 'et-quoniam-apud');
?>

<div class="bulma-section cm-footer-top cm-is-gris-dark">
  <div class="bulma-container">
    <h2 class="has-text-centered is-size-2">Our world</h2>
  </div>
</div>

<div class="bulma-section cm-footer-center cm-is-gris-doux pt-0">
  <div class="bulma-container">
    <div class="bulma-columns has-text-centered">
      <div class="bulma-column">
        <h4 class="cm-is-spaced mt-6 mb-3">Follow us</h4>
        <ul class="cm-socials">
          <li><i class="fab fa-youtube"></i></li>
          <li><i class="fab fa-facebook-f"></i></li>
          <li><i class="fab fa-instagram"></i></li>
          <li><i class="fab fa-linkedin-in"></i></li>
          <li><i class="fab fa-vimeo-v"></i></li>
        </ul>
        <h4 class="cm-is-spaced mt-6 mb-3">Read us</h4>
        <?php echo $this->partial('common/forms/newsletter'); ?>
      </div>
      <div class="bulma-column">
        <h4 class="cm-is-spaced mt-6 mb-3">Explore</h4>
        <?php echo $this->partial('common/footer/footer-menu'); ?>
        <h4 class="cm-is-spaced mt-6 mb-3">Bonus</h4>
        <ul>
          <li><a href="/notice">Notice</a></li>
          <li><a href="/notice#thanks">Thanks</a></li>
        </ul>
      </div>
      <div class="bulma-column">
        <h4 class="cm-is-spaced mt-6 mb-3">Find us</h4>
        <p>Address #1<br/>Address #2</p>
        <p><i class="fas fa-at"></i> email</p>
        <p><i class="fas fa-phone"></i> phone</p>
      </div>
    </div>
  </div>
</div>

<div class="bulma-section cm-footer-bottom cm-is-gris-medium p-2">
  <div class="bulma-container">
    <div class="has-text-centered">&copy; copyright</div>
  </div>
</div>

<!-- template end: common/footer/footer -->
