<?php
//include './themes/boregar-papyrus/asset/debug/kint.phar';
//Kint::$depth_limit = 3;

$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));

// libraries begin
$this->headLink()->appendStylesheet($this->assetUrl('libraries/bulma/css/versions/bulma-prefixed-no-dark-mode.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('libraries/bulma/extensions/timeline/bulma-timeline.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('libraries/flickity/css/flickity.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('libraries/flickity/css/flickity-fade.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/base.css'));
$this->headScript()->appendFile($this->assetUrl('libraries/fontawesome/js/fontawesome.min.js'));
$this->headScript()->appendFile($this->assetUrl('libraries/fontawesome/js/solid.min.js'));
$this->headScript()->appendFile($this->assetUrl('libraries/fontawesome/js/regular.min.js'));
$this->headScript()->appendFile($this->assetUrl('libraries/fontawesome/js/brands.min.js'));
$this->headScript()->appendFile($this->assetUrl('libraries/flickity/js/flickity.pkgd.min.js'));
$this->headScript()->appendFile($this->assetUrl('libraries/flickity/js/flickity-fade.js'));
$this->headScript()->appendFile($this->assetUrl('libraries/isotope/isotope.pkgd.min.js'));
$this->headScript()->appendFile($this->assetUrl('libraries/fslightbox/fslightbox.js'));
$this->headScript()->appendFile($this->assetUrl('libraries/openseadragon/openseadragon.js'));
$this->headScript()->appendFile($this->assetUrl('js/matomo.js'));
$this->headScript()->appendFile($this->assetUrl('js/base.js'));
// libraries end

$this->jsTranslate();
$banner = $this->themeSettingAssetUrl('banner');
$bannerHeight = $this->themeSetting('banner_height');
$bannerHeightMobile = $this->themeSetting('banner_height_mobile');
$bannerPosition = ($this->themeSetting('banner_position')) ? str_replace('_','-', $this->themeSetting('banner_position')) : 'center';
$browseBodyTruncation = ($this->themeSetting('browse_body_truncation')) ? $this->themeSetting('browse_body_truncation') : 'fade';
$this->htmlElement('body')->appendAttribute('class', 'body-truncate-' . $browseBodyTruncation);
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
  <head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
    <?php echo $this->headScript(); ?>

    <style>
      <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
      a:link,
      a:visited {
        color: <?php echo $accentColor; ?>
      }

      a:active,
      a:hover {
        color: <?php echo $accentColor; ?>;
        opacity: .75;
      }
      <?php endif; ?>

      .banner {
        height: <?php echo ($bannerHeight !== '') ? $bannerHeight: 'auto'  ?>;
        align-items: <?php echo $bannerPosition; ?>;
      }
      <?php if ($bannerHeightMobile !== ''): ?>
        @media screen and (max-width:640px) {
          .banner {
            height: <?php echo $bannerHeightMobile; ?>;
          }
        }
      <?php endif; ?>
    </style>
  </head>

  <?php echo $this->htmlElement('body'); ?>
    <a id="skipnav" class="visually-hidden" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
    <?php echo $userBar; ?>
    <a href="#" class="back-to-top"><i class="fa-solid fa-circle-chevron-up"></i></a>
    <overlay class="search bulma-modal">
      <?php echo $this->partial('common/search-form'); ?>
    </overlay>
    <overlay class="spinner"></overlay>

    <div class="layout-container mt-0 pb-0">
      <header>
        <nav class="bulma-navbar bulma-is-transparent" role="navigation">
          <div id="cm-branding" class="bulma-block">
            <div class="bulma-navbar-brand">
              <div class="bulma-navbar-item">
                <a id="cm-logo" href="/" rel="home">
                  <?php if ($this->themeSetting('logo')): ?>
                    <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                  <?php else: ?>
                    <?php echo $escape($siteTitle); ?>
                  <?php endif; ?>
                </a>
              </div>
              <a role="button" class="bulma-navbar-burger" aria-label="menu" aria-expanded="false" data-target="cm-menu">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
              </a>
            </div>
          </div>
        <div id="cm-menu" class="bulma-navbar-menu">
          <div class="bulma-navbar-end">
            <?php echo $this->partial('navigation/menu'); ?>
            <div id="cm-search-icon"></div>
          </div>
        </div>
      </nav>
      </header>
      <div id="content" role="main">
        <?php echo $this->content; ?>
      </div>
      <footer>
        <?php echo $this->partial('common/footer/footer'); ?>
      </footer>
    </div>
  </body>
</html>
